name = "anexpia/squish"
version = "6.1.1"
description = "Fork of 'Squash' with more features, optimizations, and design changes."
authors = ["anexpia"]
repository = "https://github.com/anexpia/Squish"
license = "MIT"

includes = [
  "pesde.toml",
  "README.md",
  "LICENSE",
  "src/init.luau"
]

[target]
environment = "luau"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]

[dev_dependencies]

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

